openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:50607
  description: Generated server url
paths:
  /demo/hello:
    get:
      tags:
      - demo-controller
      operationId: getHello
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
