openapi: 3.0.1
info:
  title: Demo Microcks API Def
  version: 1.0.0
servers:
- url: http://localhost:50607
  description: Generated server url
paths:
  /demo/createUser:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              user-created:
                value:
                  name: Kashyap
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                user-created:
                  value:
                    id: 12345
                    name: Kashyap
                    age: 25
          description: User created success
components:
  schemas:
    User:
      description: A sample user
      required:
        - id
        - name
        - age
      type: object
      properties:
        id:
          description: A random id long value
          type: number
        name:
          description: User name as input
          type: string
        age:
          description: User age
          type: integer