openapi: 3.0.1
info:
  title: Demo Microcks API Def
  version: 1.0.0
servers:
- url: http://localhost:50607
  description: Generated server url
paths:
  /demo/createUser:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              user-created:
                value:
                  name: Jane Doe
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                user-created:
                  value:
                    id: 12345
                    name: Jane Doe
                    age: 25
          description: User created success
  /demo/getUser/{userId}:
    get:
      summary: Get a user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of user to return
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                user-found:
                  value:
                    id: 1234567890123456789
                    name: Jane Doe
                    age: 47
components:
  schemas:
    User:
      description: A sample user
      required:
        - id
        - name
        - age
      type: object
      properties:
        id:
          description: A random id long value
          type: number
        name:
          description: User name as input
          type: string
        age:
          description: User age
          type: integer